name: Dummy Workflow
on: workflow_dispatch

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello
        run: echo "Hello Sasha"
      - name: Print Goodbye
        run: echo "Bye Sasha"
    
